### ISSUE TITLE
APPEND is unnecessary @ PadType

### ISSUE THREAD

**Issue by Hattorius** [lvkdotsh/logger#19]
[PadType](https://github.com/lvkdotsh/logger/blob/master/src/types.ts#L7) doesn't need the `APPEND` option. Will never be used and looks ugly.

**Comment by svemat01** [comment]
IMO, I think Append looks better then Prepend. No need to remove it.

**Comment by lucemans** [comment]
I think we have established a legitimate userbase/case for this functionality and will therefore close this issue.
