### ISSUE TITLE
Configure the padding character

### ISSUE THREAD

**Issue by lucemans** [lvkdotsh/logger#32]

**Comment by lucemans** [comment]
Before:
![image](https://user-images.githubusercontent.com/10339043/146007182-fb0416af-36f5-4d5d-bed3-a11bd982064b.png)
After:
![image](https://user-images.githubusercontent.com/10339043/146008136-4ecfc429-1085-4c1b-a9bb-d96ff731d772.png)

**Comment by Hattorius** [comment]
Cool!
