### ISSUE TITLE
add a log file option in the createLogger

### ISSUE THREAD

**Issue by athyk** [lvkdotsh/logger#49]
Possible syntax for a file in the same folder:

```js
createLogger({
     error: `ERROR`,
     file: "log.txt",
})
```

Or pass a path to it instead:

```js
createLogger({
     error: `ERROR`,
     file: join(__dirname, "log.txt"),
})
```

Optionally

```js
createLogger({
     error: `ERROR`,
     folder: 'logs',
})
```

This would create a log of every run in the `logs` folder in a possible look like:

```
logs/
├─ log_2021-12-21-12-08-54
├─ log_2021-12-21-12-06-51
```

**Comment by lucemans** [comment]
Idea for how we could have the final implementation behave...
![image](https://user-images.githubusercontent.com/10339043/146930607-bef500af-6949-444f-be9e-6c97913a8365.png)
