### ISSUE TITLE
[Feature] Multiple Output Functions

### ISSUE THREAD

**Issue by lucemans** [lvkdotsh/logger#51]
**Is your feature request related to a problem? Please describe.**
Multiple output functions so the log can both be `console.log`-ed aswell as sent to file etc

**Describe the solution you'd like**
Be able to provide an array of functions to the logger output function variable which all ought to be excuted.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by athyk** [comment]
Webhook post request as a function for output
