### ISSUE TITLE
[Feature] Get Line number and file name within logging 

### ISSUE THREAD

**Issue by athyk** [lvkdotsh/logger#78]
**Is your feature request related to a problem? Please describe.**
When you have a large amount of code that you would want to log and keep the logging there if enabled such as a development version of a project. An example would be `[DEBUG] user is undefined Line 347 of /src/index.js`

**Describe the solution you'd like**
```js
log.debug($`user is ${user} Line ${log.line} of ${log.path}`);
```

**Comment by lucemans** [comment]
Extension of #64

**Comment by lucemans** [comment]
Closing this issue due to duplicate
